scripts/installer.py
(http://i.imgur.com/iIqZ01l.png)
=> Added "To remove" and "To install" info to the confirm dialog

scripts/installer.py
Silly me, removing elements from lists I'm looping over :)
=> Fix removing from lists

install.py, install.sh, scripts/apps.elementaryPlusInstaller.gschema.xml, scripts/core/core.sh, scripts/core/core_remove.sh, scripts/install_schema.sh, scripts/megasync/megasync.sh, scripts/megasync/megasync_remove.sh, scripts/owncloud/owncloud.sh, scripts/owncloud/owncloud_remove.sh, scripts/skype/skype.sh, scripts/skype/skype_remove.sh, scripts/sni-qt.sh
Also, new patched sni-qt now uses icons from ~/.local/share/sni-qt/icons instead of /usr/share/sni-qt/icons
=> Autoselect theme when installed

elementaryPlus/status/24/state-error.svg, elementaryPlus/status/24/state-information.svg, elementaryPlus/status/24/state-offline.svg, elementaryPlus/status/24/state-ok.svg, elementaryPlus/status/24/state-pause.svg, elementaryPlus/status/24/state-sync.svg, elementaryPlus/status/48/state-error.svg, elementaryPlus/status/48/state-information.svg, elementaryPlus/status/48/state-offline.svg, elementaryPlus/status/48/state-ok.svg, elementaryPlus/status/48/state-pause.svg, elementaryPlus/status/48/state-sync.svg
=> Update symlinks for Owncloud

CREDITS.md, elementaryPlus/apps/16/minecraft.svg, elementaryPlus/apps/32/minecraft.svg, elementaryPlus/apps/48/minecraft.svg, elementaryPlus/apps/64/minecraft.svg
"to use as you see fit" by hewittsamuel
http://hewittsamuel.deviantart.com/art/elementary-style-Minecraft-Icons-483281501
=> Minecraft added

CREDITS.md, elementaryPlus/apps/128/chromium-browser.svg, elementaryPlus/apps/128/transmission.svg, elementaryPlus/apps/128/virtualbox.svg, elementaryPlus/apps/16/chromium-browser.svg, elementaryPlus/apps/16/transmission.svg, elementaryPlus/apps/16/virtualbox.svg, elementaryPlus/apps/22/chromium-browser.svg, elementaryPlus/apps/22/transmission.svg, elementaryPlus/apps/22/virtualbox.svg, elementaryPlus/apps/24/chromium-browser.svg, elementaryPlus/apps/24/transmission.svg, elementaryPlus/apps/24/virtualbox.svg, elementaryPlus/apps/32/chromium-browser.svg, elementaryPlus/apps/32/transmission.svg, elementaryPlus/apps/32/virtualbox.svg, elementaryPlus/apps/48/chromium-browser.svg, elementaryPlus/apps/48/transmission.svg, elementaryPlus/apps/48/virtualbox.svg, elementaryPlus/apps/64/chromium-browser.svg, elementaryPlus/apps/64/transmission.svg, elementaryPlus/apps/64/virtualbox.svg
by ori: http://ori.iblogger.org/icons/
permission:
http://ori.iblogger.org/virtualbox-icons-for-elementary-os/#comment-1920104622
=> Chromium, Transmission, Virtualbox added

elementaryPlus/status/24/edit-find-symbolic.svg, elementaryPlus/status/24/redshift-status-off.svg, elementaryPlus/status/24/redshift-status-on.svg
I pull request redshift and synpase-indicator fixed.
=> Some icons added

elementaryPlus/apps/128/brackets.svg, elementaryPlus/apps/16/brackets.svg, elementaryPlus/apps/22/brackets.svg, elementaryPlus/apps/24/brackets.svg, elementaryPlus/apps/32/brackets.svg, elementaryPlus/apps/48/brackets.svg, elementaryPlus/apps/64/brackets.svg
Hey guys I just added an old icon that I did for brackets.
Hope you like. Here do you have a preview.
=> brackets icon

elementaryPlus/status/24/copyq-busy.svg, elementaryPlus/status/24/copyq-normal.svg
elementary OS styled CopyQ indicator icons
=> CopyQ indicator icons

elementaryPlus/status/24/redshift-status-off.svg, elementaryPlus/status/24/redshift-status-on.svg
A little enhancement for redshift, the icon look better now.
=> redshift indicator enhanced

elementaryPlus/apps/128/tweetdeck.svg, elementaryPlus/apps/16/tweetdeck.svg, elementaryPlus/apps/22/tweetdeck.svg, elementaryPlus/apps/24/tweetdeck.svg, elementaryPlus/apps/32/tweetdeck.svg, elementaryPlus/apps/48/tweetdeck.svg, elementaryPlus/apps/64/tweetdeck.svg
Sorry to pull request again. Just creating different branch for different elements that I will pull request.
=> new tweetdeck icon

elementaryPlus/status/24/hipchat-attention.svg, elementaryPlus/status/24/hipchat-panel.svg
=> HipChat indicator icons

elementaryPlus/status/24/uget-tray-default.svg, elementaryPlus/status/24/uget-tray-downloading.svg, elementaryPlus/status/24/uget-tray-error.svg
=> uGet indicator icons

elementaryPlus/status/24/deluge-panel.svg, elementaryPlus/status/24/transmission-tray-icon.svg
=> Deluge & Transmission indicator icons

scripts/elementaryplus-installer.py
@bil-elmoussaoui's pull request had some conflicts so here are his changes + some fixes by me.
Also, `components` is now a list (as opposed to a dictionary). This makes sorting possible (We want components sorted in alphabetical order)
=> Detecting installed apps

elementaryPlus/apps/128/code.svg, elementaryPlus/apps/128/visualstudiocode.svg, elementaryPlus/apps/128/vscode.svg, elementaryPlus/apps/16/code.svg, elementaryPlus/apps/16/visualstudiocode.svg, elementaryPlus/apps/16/vscode.svg, elementaryPlus/apps/24/code.svg, elementaryPlus/apps/24/visualstudiocode.svg, elementaryPlus/apps/24/vscode.svg, elementaryPlus/apps/32/code.svg, elementaryPlus/apps/32/visualstudiocode.svg, elementaryPlus/apps/32/vscode.svg, elementaryPlus/apps/48/code.svg, elementaryPlus/apps/48/visualstudiocode.svg, elementaryPlus/apps/48/vscode.svg, elementaryPlus/apps/64/code.svg, elementaryPlus/apps/64/visualstudiocode.svg, elementaryPlus/apps/64/vscode.svg
=> Visual Studio Code app icon

elementaryPlus/status/24/keepassx-panel.svg
=> KeepassX indicator icon

elementaryPlus/status/24/dropboxstatus-busy.svg, elementaryPlus/status/24/dropboxstatus-busy2.svg, elementaryPlus/status/24/dropboxstatus-idle.svg, elementaryPlus/status/24/dropboxstatus-logo.svg, elementaryPlus/status/24/dropboxstatus-x.svg
How about a more recognizable Dropbox indicator icon?
=> new Dropbox indicator icons

elementaryPlus/status/24/caffeine-cup-empty.svg, elementaryPlus/status/24/caffeine-cup-full.svg
=> caffeine indicators changed

elementaryPlus/status/24/scudcloud-attention-1.svg, elementaryPlus/status/24/scudcloud-attention-2.svg, elementaryPlus/status/24/scudcloud-attention-3.svg, elementaryPlus/status/24/scudcloud-attention-4.svg, elementaryPlus/status/24/scudcloud-attention-5.svg, elementaryPlus/status/24/scudcloud-attention-6.svg, elementaryPlus/status/24/scudcloud-attention-7.svg, elementaryPlus/status/24/scudcloud-attention-8.svg, elementaryPlus/status/24/scudcloud-attention-9-plus.svg, elementaryPlus/status/24/scudcloud-attention-9.svg, elementaryPlus/status/24/scudcloud-attention.svg, elementaryPlus/status/24/scudcloud-panel.svg
=> ScudCloud indicator icons

elementaryPlus/status/24/network-idle.svg, elementaryPlus/status/24/network-receive.svg, elementaryPlus/status/24/network-transmit-receive.svg, elementaryPlus/status/24/network-transmit.svg
=> Netspeed indicator icons

elementaryPlus/status/24/clipit-trayicon.svg, elementaryPlus/status/24/edit-paste-panel.svg, elementaryPlus/status/24/gtk-paste-panel.svg
Just some symbolic links to add support for GPaste, ClipIt and Parcellite
=> Support for some other clipboardmanager indicator icons

elementaryPlus/status/24/syspeek-0.svg, elementaryPlus/status/24/syspeek-10.svg, elementaryPlus/status/24/syspeek-100.svg, elementaryPlus/status/24/syspeek-20.svg, elementaryPlus/status/24/syspeek-30.svg, elementaryPlus/status/24/syspeek-40.svg, elementaryPlus/status/24/syspeek-50.svg, elementaryPlus/status/24/syspeek-60.svg, elementaryPlus/status/24/syspeek-70.svg, elementaryPlus/status/24/syspeek-80.svg, elementaryPlus/status/24/syspeek-90.svg
there are of course all 10%-steps
=> Syspeek indicator icons

elementaryPlus/status/24/fluxgui-panel.svg
=> f.lux indicator icon

elementaryPlus/status/24/indicator-feedindicator-attention.svg, elementaryPlus/status/24/indicator-feedindicator.svg, elementaryPlus/status/24/indicator-rss-aware-attention.svg, elementaryPlus/status/24/indicator-rss-aware.svg
=> RSS Aware and Feedindicator icons

elementaryPlus/status/24/everpad-mono.svg
=> Everpad indicator icon

elementaryPlus/status/24/qbittorrent-panel.svg
=> qBittorrent indicator icon

elementaryPlus/status/24/psensor_hot.svg, elementaryPlus/status/24/psensor_normal.svg
=> PSensor indicator icons

elementaryPlus/status/24/vlc-panel.svg
=> VLC indicator icon ...yet another app that doesn't need one

elementaryPlus/status/24/indicator-sound-switcher.svg
=> Sound switcher indicator icon

elementaryPlus/apps/128/Pencil.svg, elementaryPlus/apps/16/Pencil.svg, elementaryPlus/apps/24/Pencil.svg, elementaryPlus/apps/32/Pencil.svg, elementaryPlus/apps/48/Pencil.svg, elementaryPlus/apps/64/Pencil.svg
[Pencil](https://github.com/prikhi/pencil) is a very nice  GUI prototyping tool with a hideous icon
=> Pencil application icon

elementaryPlus/apps/128/utilities-system-monitor.svg, elementaryPlus/apps/16/utilities-system-monitor.svg, elementaryPlus/apps/24/utilities-system-monitor.svg, elementaryPlus/apps/32/utilities-system-monitor.svg, elementaryPlus/apps/48/utilities-system-monitor.svg, elementaryPlus/apps/64/utilities-system-monitor.svg
created by Daniel Foré, licensed under GPL
=> Gnome System Monitor icons, fixes #163

elementaryPlus/status/24/alarm-clock-panel.svg, elementaryPlus/status/24/alarm-clock-triggered.svg
GitHub doesn't let me upload a screenshot... but it looks really nice ;)
=> Alarm Clock Panel indicator icons

elementaryPlus/status/24/indicator-notification-read.svg, elementaryPlus/status/24/indicator-notification-unread.svg, elementaryPlus/status/24/notification-read.svg, elementaryPlus/status/24/notification-unread.svg
=> Recent Notifications indicator icons

scripts/custom.css, scripts/elementaryplus-installer.py
What do you guys think? @mank319 @quassy
=> New installer design

scripts/elementaryplus-installer.py
Will now set the full app description as a tooltip even for apps that are not installed. The search filter will use the tooltip text for searching.
=> Search full description

elementaryPlus/status/24/indicator-processor.svg
just a modified cpufreq-indicator icon for [Power Gadget](https://bitbucket.org/baltic/power-gadget/overview)
=> Power-Gadget indicator icon

elementaryPlus/status/24/indicator-remindor-active.svg, elementaryPlus/status/24/indicator-remindor-attention.svg, elementaryPlus/status/24/indicator-remindor-error.svg
=> Indicator Remindor icons

elementaryPlus/status/24/classicmenu-indicator.svg
=> Classic Menu indicator icon

scripts/elementaryplus-installer.py
This will show installed apps on the top of the list (still sorted alphabetically).
=> Show installed apps first

scripts/elementaryplus-installer.py
Resets switch if error is encountered.
=> Handle errors

elementaryPlus/status/24/remmina-panel.svg
=> Remmina indicator icons

elementaryPlus/apps/128/chrome-https___www.messenger.com.svg, elementaryPlus/apps/128/chrome-https___www.messenger.com_.svg, elementaryPlus/apps/128/chrome-https___www.messenger.com___rdr.svg, elementaryPlus/apps/128/messengerfordesktop.svg, elementaryPlus/apps/16/chrome-https___www.messenger.com.svg, elementaryPlus/apps/16/chrome-https___www.messenger.com_.svg, elementaryPlus/apps/16/chrome-https___www.messenger.com___rdr.svg, elementaryPlus/apps/16/messengerfordesktop.svg, elementaryPlus/apps/24/chrome-https___www.messenger.com.svg, elementaryPlus/apps/24/chrome-https___www.messenger.com_.svg, elementaryPlus/apps/24/chrome-https___www.messenger.com___rdr.svg, elementaryPlus/apps/24/messengerfordesktop.svg, elementaryPlus/apps/32/chrome-https___www.messenger.com.svg, elementaryPlus/apps/32/chrome-https___www.messenger.com_.svg, elementaryPlus/apps/32/chrome-https___www.messenger.com___rdr.svg, elementaryPlus/apps/32/messengerfordesktop.svg, elementaryPlus/apps/48/chrome-https___www.messenger.com.svg, elementaryPlus/apps/48/chrome-https___www.messenger.com_.svg, elementaryPlus/apps/48/chrome-https___www.messenger.com___rdr.svg, elementaryPlus/apps/48/messengerfordesktop.svg, elementaryPlus/apps/64/chrome-https___www.messenger.com.svg, elementaryPlus/apps/64/chrome-https___www.messenger.com_.svg, elementaryPlus/apps/64/chrome-https___www.messenger.com___rdr.svg, elementaryPlus/apps/64/messengerfordesktop.svg
=> facebook Messenger icon

scripts/custom/core_icon_theme.py, scripts/custom/spotify.py, scripts/custom/telegram_desktop.py, scripts/elementaryplus-installer.py
* Got rid of the "Apply" button, everything install instantly now.
* Better error handling!
* Better install management.
* More fixes!
=> Major improvements

elementaryPlus/apps/128/virtualbox.svg
Lowered the shadow object.
Before:
After:
=> Fix VirtualBox shadow

elementaryPlus/apps/128/virtualbox.svg
Reverts mank319/elementaryPlus#236
=> Revert "Fix VirtualBox shadow"

scripts/elementaryplus-installer.py
Haha, forgot to actually replace the variable when I thought I've fixed it.
=> Fix install process

elementaryPlus/apps/128/vlc.svg, elementaryPlus/apps/16/vlc.svg, elementaryPlus/apps/22/vlc.svg, elementaryPlus/apps/24/vlc.svg, elementaryPlus/apps/32/vlc.svg, elementaryPlus/apps/48/vlc.svg, elementaryPlus/apps/64/vlc.svg
[VLC icons](http://spg76.deviantart.com/art/VLC-elementary-style-173346228?q=gallery%3Aspg76%2F6097980&qo=8), part of [elementary extras](http://spg76.deviantart.com/art/elementary-extras-Icons-215459969) by spg76 released under GPL
=> Add VLC icons, fix #244

elementaryPlus/status/24/indicator-ppa-download-statistics-panel.svg
only a link to Y-PPA-indicator
=> PPA download statistics indicator icon

elementaryPlus/status/24/nitroshare-indicator.svg
=> NitroShare indicator icon

elementaryPlus/status/24/system-file-manager-panel.svg
=> Places indicator icon

scripts/custom/telegram_desktop.py
Fixed problem with missing `icomute_22_1.png` link.
=> Fix telegram indicator icons

elementaryPlus/status/24/cryptkeeper-panel.svg
=> Cryptkeeper indicator icon

elementaryPlus/status/24/haguichi-connected.svg, elementaryPlus/status/24/haguichi-connecting-1.svg, elementaryPlus/status/24/haguichi-connecting-2.svg, elementaryPlus/status/24/haguichi-connecting-3.svg, elementaryPlus/status/24/haguichi-disconnected.svg
=> Haguichi indicator icons, fixes #293

elementaryPlus/apps/128/timeshift.svg, elementaryPlus/apps/32/timeshift.svg, elementaryPlus/apps/48/timeshift.svg, elementaryPlus/apps/64/timeshift.svg
…://github.com/mank319/elementaryPlus/issues/294
As requested [here.](https://github.com/mank319/elementaryPlus/issues/294)
=> Add ../apps/../timeshift.svg (32,48,64,128px)

elementaryPlus/apps/128/codeblocks.svg, elementaryPlus/apps/16/codeblocks.svg, elementaryPlus/apps/24/codeblocks.svg, elementaryPlus/apps/32/codeblocks.svg, elementaryPlus/apps/48/codeblocks.svg, elementaryPlus/apps/64/codeblocks.svg
As requested [here.](https://github.com/mank319/elementaryPlus/issues/310)
=> Add codeblocks

elementaryPlus/apps/128/openshot.svg, elementaryPlus/apps/16/openshot.svg, elementaryPlus/apps/16/timeshift.svg, elementaryPlus/apps/24/openshot.svg, elementaryPlus/apps/24/timeshift.svg, elementaryPlus/apps/32/openshot.svg, elementaryPlus/apps/48/openshot.svg, elementaryPlus/apps/64/openshot.svg
As requested here https://github.com/mank319/elementaryPlus/issues/294 and here https://github.com/mank319/elementaryPlus/issues/292
=> Add timeshift 16 & 24px and openshot (all sizes)

elementaryPlus/apps/128/teamviewer.svg, elementaryPlus/apps/16/teamviewer.svg, elementaryPlus/apps/24/teamviewer.svg, elementaryPlus/apps/32/teamviewer.svg, elementaryPlus/apps/48/teamviewer.svg, elementaryPlus/apps/64/teamviewer.svg
=> Teamviewer icons by Daniel Foré, fixes #318

elementaryPlus/apps/128/FoxitReader.svg, elementaryPlus/apps/16/FoxitReader.svg, elementaryPlus/apps/24/FoxitReader.svg, elementaryPlus/apps/32/FoxitReader.svg, elementaryPlus/apps/48/FoxitReader.svg, elementaryPlus/apps/64/FoxitReader.svg
As requested [here.](https://github.com/mank319/elementaryPlus/issues/332)
=> Add FoxitReader.svg

elementaryPlus/apps/128/viewnior.svg, elementaryPlus/apps/16/viewnior.svg, elementaryPlus/apps/24/viewnior.svg, elementaryPlus/apps/32/viewnior.svg, elementaryPlus/apps/48/viewnior.svg, elementaryPlus/apps/64/viewnior.svg
=> Add viewnior

elementaryPlus/apps/128/texmaker.svg, elementaryPlus/apps/16/texmaker.svg, elementaryPlus/apps/24/texmaker.svg, elementaryPlus/apps/32/texmaker.svg, elementaryPlus/apps/48/texmaker.svg, elementaryPlus/apps/64/texmaker.svg
=> Add texmaker

elementaryPlus/apps/128/rstudio.svg, elementaryPlus/apps/16/rstudio.svg, elementaryPlus/apps/24/rstudio.svg, elementaryPlus/apps/32/rstudio.svg, elementaryPlus/apps/48/rstudio.svg, elementaryPlus/apps/64/rstudio.svg
Partial fix for 309 (rproject still required)
=> Add rstudio

elementaryPlus/apps/128/chrome-knipolnnllmklapflnccelgolnpehhpl-Default.svg, elementaryPlus/apps/128/hangouts.svg, elementaryPlus/apps/128/mega.svg, elementaryPlus/apps/16/chrome-knipolnnllmklapflnccelgolnpehhpl-Default.svg, elementaryPlus/apps/16/hangouts.svg, elementaryPlus/apps/16/mega.svg, elementaryPlus/apps/24/chrome-knipolnnllmklapflnccelgolnpehhpl-Default.svg, elementaryPlus/apps/24/hangouts.svg, elementaryPlus/apps/24/mega.svg, elementaryPlus/apps/32/chrome-knipolnnllmklapflnccelgolnpehhpl-Default.svg, elementaryPlus/apps/32/hangouts.svg, elementaryPlus/apps/32/mega.svg, elementaryPlus/apps/48/chrome-knipolnnllmklapflnccelgolnpehhpl-Default.svg, elementaryPlus/apps/48/hangouts.svg, elementaryPlus/apps/48/mega.svg, elementaryPlus/apps/64/chrome-knipolnnllmklapflnccelgolnpehhpl-Default.svg, elementaryPlus/apps/64/hangouts.svg, elementaryPlus/apps/64/mega.svg
=> Added Hangouts and MEGA icons, fixes #240 & #371

elementaryPlus/apps/128/zsnes.svg, elementaryPlus/apps/16/zsnes.svg, elementaryPlus/apps/24/zsnes.svg, elementaryPlus/apps/32/zsnes.svg, elementaryPlus/apps/48/zsnes.svg, elementaryPlus/apps/64/zsnes.svg
=> Added Zsnes icon

elementaryPlus/apps/128/snes9x.svg, elementaryPlus/apps/16/snes9x.svg, elementaryPlus/apps/24/snes9x.svg, elementaryPlus/apps/32/snes9x.svg, elementaryPlus/apps/48/snes9x.svg, elementaryPlus/apps/64/snes9x.svg
Here is a preview of the icons added:
=> Added Snes9x icons

elementaryPlus/apps/128/obs.svg, elementaryPlus/apps/16/obs.svg, elementaryPlus/apps/24/obs.svg, elementaryPlus/apps/32/obs.svg, elementaryPlus/apps/48/obs.svg, elementaryPlus/apps/64/obs.svg
=> Add OBS Icon

elementaryPlus/apps/128/nvidia-settings.svg, elementaryPlus/apps/16/nvidia-settings.svg, elementaryPlus/apps/24/nvidia-settings.svg, elementaryPlus/apps/32/nvidia-settings.svg, elementaryPlus/apps/48/nvidia-settings.svg, elementaryPlus/apps/64/nvidia-settings.svg
=> Add Nvidia-Settings Icon

elementaryPlus/apps/128/nvidia-settings.svg, elementaryPlus/apps/128/softwarecenter.svg, elementaryPlus/apps/16/nvidia-settings.svg, elementaryPlus/apps/16/softwarecenter.svg, elementaryPlus/apps/24/nvidia-settings.svg, elementaryPlus/apps/24/softwarecenter.svg, elementaryPlus/apps/32/nvidia-settings.svg, elementaryPlus/apps/32/softwarecenter.svg, elementaryPlus/apps/48/nvidia-settings.svg, elementaryPlus/apps/48/softwarecenter.svg, elementaryPlus/apps/64/nvidia-settings.svg, elementaryPlus/apps/64/softwarecenter.svg
=> Add Software Center and Nvidia Settings icons
